/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    JetstreamActionMessage: typeof import('./resources/js/Components/Jetstream/ActionMessage.vue')['default']
    JetstreamActionSection: typeof import('./resources/js/Components/Jetstream/ActionSection.vue')['default']
    JetstreamApplicationLogo: typeof import('./resources/js/Components/Jetstream/ApplicationLogo.vue')['default']
    JetstreamApplicationMark: typeof import('./resources/js/Components/Jetstream/ApplicationMark.vue')['default']
    JetstreamAuthenticationCard: typeof import('./resources/js/Components/Jetstream/AuthenticationCard.vue')['default']
    JetstreamAuthenticationCardLogo: typeof import('./resources/js/Components/Jetstream/AuthenticationCardLogo.vue')['default']
    JetstreamBanner: typeof import('./resources/js/Components/Jetstream/Banner.vue')['default']
    JetstreamCheckbox: typeof import('./resources/js/Components/Jetstream/Checkbox.vue')['default']
    JetstreamConfirmationModal: typeof import('./resources/js/Components/Jetstream/ConfirmationModal.vue')['default']
    JetstreamConfirmsPassword: typeof import('./resources/js/Components/Jetstream/ConfirmsPassword.vue')['default']
    JetstreamDangerButton: typeof import('./resources/js/Components/Jetstream/DangerButton.vue')['default']
    JetstreamDialogModal: typeof import('./resources/js/Components/Jetstream/DialogModal.vue')['default']
    JetstreamDropdown: typeof import('./resources/js/Components/Jetstream/Dropdown.vue')['default']
    JetstreamDropdownLink: typeof import('./resources/js/Components/Jetstream/DropdownLink.vue')['default']
    JetstreamFormSection: typeof import('./resources/js/Components/Jetstream/FormSection.vue')['default']
    JetstreamInputError: typeof import('./resources/js/Components/Jetstream/InputError.vue')['default']
    JetstreamInputLabel: typeof import('./resources/js/Components/Jetstream/InputLabel.vue')['default']
    JetstreamModal: typeof import('./resources/js/Components/Jetstream/Modal.vue')['default']
    JetstreamNavLink: typeof import('./resources/js/Components/Jetstream/NavLink.vue')['default']
    JetstreamPrimaryButton: typeof import('./resources/js/Components/Jetstream/PrimaryButton.vue')['default']
    JetstreamResponsiveNavLink: typeof import('./resources/js/Components/Jetstream/ResponsiveNavLink.vue')['default']
    JetstreamSecondaryButton: typeof import('./resources/js/Components/Jetstream/SecondaryButton.vue')['default']
    JetstreamSectionBorder: typeof import('./resources/js/Components/Jetstream/SectionBorder.vue')['default']
    JetstreamSectionTitle: typeof import('./resources/js/Components/Jetstream/SectionTitle.vue')['default']
    JetstreamTextInput: typeof import('./resources/js/Components/Jetstream/TextInput.vue')['default']
    JetstreamWelcome: typeof import('./resources/js/Components/Jetstream/Welcome.vue')['default']
  }
}
