/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionMessage: typeof import('./resources/js/Components/ActionMessage.vue')['default']
    ActionSection: typeof import('./resources/js/Components/ActionSection.vue')['default']
    AppLayout: typeof import('./resources/js/Layouts/AppLayout.vue')['default']
    ApplicationLogo: typeof import('./resources/js/Components/ApplicationLogo.vue')['default']
    ApplicationMark: typeof import('./resources/js/Components/ApplicationMark.vue')['default']
    AuthenticationCard: typeof import('./resources/js/Components/AuthenticationCard.vue')['default']
    AuthenticationCardLogo: typeof import('./resources/js/Components/AuthenticationCardLogo.vue')['default']
    Banner: typeof import('./resources/js/Components/Banner.vue')['default']
    Checkbox: typeof import('./resources/js/Components/Checkbox.vue')['default']
    ConfirmationModal: typeof import('./resources/js/Components/ConfirmationModal.vue')['default']
    ConfirmsPassword: typeof import('./resources/js/Components/ConfirmsPassword.vue')['default']
    DangerButton: typeof import('./resources/js/Components/DangerButton.vue')['default']
    DialogModal: typeof import('./resources/js/Components/DialogModal.vue')['default']
    Dropdown: typeof import('./resources/js/Components/Dropdown.vue')['default']
    DropdownLink: typeof import('./resources/js/Components/DropdownLink.vue')['default']
    FormSection: typeof import('./resources/js/Components/FormSection.vue')['default']
    InputError: typeof import('./resources/js/Components/InputError.vue')['default']
    InputLabel: typeof import('./resources/js/Components/InputLabel.vue')['default']
    Modal: typeof import('./resources/js/Components/Modal.vue')['default']
    NavLink: typeof import('./resources/js/Components/NavLink.vue')['default']
    PrimaryButton: typeof import('./resources/js/Components/PrimaryButton.vue')['default']
    ResponsiveNavLink: typeof import('./resources/js/Components/ResponsiveNavLink.vue')['default']
    SecondaryButton: typeof import('./resources/js/Components/SecondaryButton.vue')['default']
    SectionBorder: typeof import('./resources/js/Components/SectionBorder.vue')['default']
    SectionTitle: typeof import('./resources/js/Components/SectionTitle.vue')['default']
    TextInput: typeof import('./resources/js/Components/TextInput.vue')['default']
    Welcome: typeof import('./resources/js/Components/Welcome.vue')['default']
  }
}
