/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by laravel-typescriptable
declare namespace Inertia {
  type Errors = Record<string, string>
  type ErrorBag = Record<string, Errors>
  interface Page {
    component: string
    props: {
      user: App.Models.User
      jetstream?: {
        canCreateTeams?: boolean
        hasTeamFeatures?: boolean
        managesProfilePhotos?: boolean
        hasApiFeatures?: boolean
        canUpdateProfileInformation?: boolean
        canUpdatePassword?: boolean
        canManageTwoFactorAuthentication?: boolean
        hasAccountDeletionFeatures?: boolean
        hasEmailVerification?: boolean
        flash?: {
          bannerStyle?: string
          banner?: string
          message?: string
          style?: string
        }
      }
      [key: string]: unknown
      errors: Inertia.Errors & Inertia.ErrorBag
    }
    url: string
    version: string | null
    scrollRegions: Array<{
      top: number
      left: number
    }>
    errors: Inertia.Errors & Inertia.ErrorBag
    rememberedState: Record<string, unknown>
    resolvedErrors: Inertia.Errors
  }
}
