// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Action: typeof import('./components/field/rich-text/action.vue')['default']
    Default: typeof import('./layouts/Default.vue')['default']
    Editor: typeof import('./components/field/rich-text/editor.vue')['default']
    Guest: typeof import('./layouts/Guest.vue')['default']
    Hello: typeof import('./components/hello.vue')['default']
    Register: typeof import('./components/form/register.vue')['default']
    RichText: typeof import('./components/field/rich-text.vue')['default']
  }
}

export { }
